### ISSUE TITLE
Add support for multiple object relationships

### ISSUE THREAD

**Issue by deejay-hub** [deejay-hub/timeline-lwc#10]
**Is your feature request related to a problem? Please describe.**
Currently the Apex code is looking up the relationship name based on the SObject requested. This does not allow for multiple relationships to the same SObject.

**Describe the solution you'd like**
Add a relationship field to the Timeline Configuration metadata type and use that in the SOQL query.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by deejay-hub** [comment]
Duplicate of issue #25 closing as this issue has a better write up on the issue at hand

**Comment by eschweitzer78** [comment]
Hi DJ, this would actually also fix issues for PersonAccounts -- they indeed have multiple relationships for Events, Tasks, and Cases, one for Account and the other one for Contact.

Thanks
