### ISSUE TITLE
Error "No active records for parent entity 'Order' have been found in 'Timeline_Configuration__mdt'" when adding Time Warp to Order

### ISSUE THREAD

**Issue by mickag69** [deejay-hub/timeline-lwc#101]
**Describe the bug**

No active records for parent entity 'Order' have been found in 'Timeline_Configuration__mdt

can you add Order in timeline ?

**Comment by deejay-hub** [comment]
Hi @mickag69 thanks for getting involved in logging issues for the Time Warp component. It looks like you're adding the Time Warp component to the standard object 'Order' and you're getting the error message you stated above. This error is documented in our Knowledge Base (https://salesforce.quip.com/6yvoAcBukqZB).

To use the Time Warp component with Order (or any other object not covered in the configuration guide https://salesforce.quip.com/ahFCA9VBEKtr) you will have to add the records to a custom metadata type yourself.  The configuration guide link walks you through how to plot standard, custom and junction objects.

Any follow up questions let us know.

**Comment by deejay-hub** [comment]
Closing issue. Since Time Warp can be added to the Order page - by design the end user needs to add the records to plot to the timeline_configuration_mdt. Time Warp will provide default values for high value targets (like Contact and Account) only at this stage.
