### ISSUE TITLE
Not all records (custom object) showing up on timeline

### ISSUE THREAD

**Issue by lindyrogers** [deejay-hub/timeline-lwc#104]
**Describe the bug**
After following the config guide to plot a custom object, everything seemed to work perfectly except for not all of the records showing up on the timeline. We mapped a custom Invoice object to show on the Account record page timeline. The records (invoices) show up as far back as we've got the Historical Time Range set to (1 Year) but then they drop off around March (which isn't correct, records for this time period exist in our org) and then 11 records are randomly plotted in early May then nothing after that. This account has 474 invoices with dates between 1/15/2020 and today (1/15/2021) but the timeline doesn't plot all of the records. After changing settings to test out different configurations and then going back to the original settings, the number of records plotted differed. At one point it plotted 72 invoices when set to a historical time range of 1 year, now it's plotting 63 invoices on that setting. It also appears to count more records than are visible on the timeline? If you adjust the timeline selection to an area with no dots showing, the top of the component will say that there are more than 0 items.

**To reproduce**

1. Follow Config Guide on how to plot a custom object
2. Add component to record page keep all default settings except change Historical Time Range to 1 Year

**Expected behavior**
We expect 474 records to be plotted all throughout the timeline from 1/15/2020 up to 1/12/2021 (the date of the newest invoice on this account).

**Screenshots**

![image](https://user-images.githubusercontent.com/76748655/104739282-26f8dd80-570c-11eb-83a5-705743ee1d7f.png)
(changed the icon mid-trouble shooting...it's been changed quite a few times and hasn't had a direct effect on the issue)
![image](https://user-images.githubusercontent.com/76748655/104739409-4b54ba00-570c-11eb-9073-5ba8a3714398.png)
![image](https://user-images.githubusercontent.com/76748655/104739434-527bc800-570c-11eb-8f11-e7e628a1ce34.png)
![image](https://user-images.githubusercontent.com/76748655/104739597-7d661c00-570c-11eb-92f0-2d01892bbfba.png)

**Desktop (please complete the following information):**

-   Browser - Google Chrome and Microsoft Edge
-   Version - Chrome 87.0.4280.141, Edge 87.0.664.75

**Additional context**
Nailing down the specifics on this issue was a little difficult... so I apologize in advance if this isn't as clear and concise as you would hope for!!

**Comment by deejay-hub** [comment]
Oh wow. There's never such thing as too much information @lindyrogers this is a great example of the level of detail we need to triage issues quickly - kudos and thanks for taking the time to give us so much info. Consider this under investigation and we'll get back to you with outcomes.

**Comment by deejay-hub** [comment]
@lindyrogers would it be possible for you to provide a file with the invoice_date__c field values for the 474 records you have? We just need the date - no other values. This will help us recreate the issue more easily as it's hard to guess how the records are dispersed over the 12 months.

**Comment by deejay-hub** [comment]
Thanks @lindyrogers that helped a lot. I created a custom object called Invoice_Header__c created a field of type Date and another field as a lookup to Contact. Then I inserted all the records with the same date values as your test spreadsheet and assigned them all to one contact. We had 474 invoice headers in your field and I created an additional one to make 475.

At first glance the time warp looks to plot them all successfully - so there might be something else at play here.
<img width="1424" alt="Invoice Headers" src="https://user-images.githubusercontent.com/7021883/105646169-8b792100-5ef2-11eb-9b95-6efb2e8149bc.png">

Can I ask you to confirm the Account Id for your records is the same value for all Invoice Headers you expect to see?  Obviously we want to rule out the possibility that some records are assigned to another Account.

**Comment by lindyrogers** [comment]
Answers to your follow-up questions:
1. Yes they are for the same account
2. We are viewing the timewarp from two system admin profiles so permission/access shouldn't be an issue
3. There are no lookup filters defined
4. Yes that query returned 494 records

Last night we uploaded the records from the file I shared with you into a sandbox and the timewarp displayed all of the records. So it seems like if we're only uploading for a single account it works as expected.. Or there's something on our record page in production that's causing the issue?

**Comment by deejay-hub** [comment]
Okay I'll keep trying. If you find steps to replicate then let me know. Otherwise we'll leave it open to see if others run into the issue.

**Comment by deejay-hub** [comment]
Thanks for the update...and glad you have it working. I'm happy to close this since you've been generous with your time. Bonus points for supplying a similar date file for your activities so we can recreate the date spread for the Tasks and Events - just to better understand the behaviour. No pressure though if it's too much hassle - we totally understand.

**Comment by lindyrogers** [comment]
Here you go! My quantities in my previous comment didn't account for tasks that were archived (I thought the numbers seemed off LOL). Thank you! 
[Task Dates.xlsx](https://github.com/deejay-hub/timeline-lwc/files/5914703/Task.Dates.xlsx)

**Comment by deejay-hub** [comment]
Root cause due to large text area field values being used in the custom metadata types. See PR#138 for details
