### ISSUE TITLE
Support for multi day events

### ISSUE THREAD

**Issue by KaushikRay** [deejay-hub/timeline-lwc#107]
**Is your feature request related to a problem? Please describe.**
Showing events spanning across multiple days. Super helpful for events and other custom from to date values

**Describe the solution you'd like**
The events come up in GANTT chart as longer in length across multiple days

**Describe alternatives you've considered**
tried some modification with the code but without much progress.

**Additional context**
We would like to show some future events which can span across multi days, so it will be great to have this feature.

**Comment by deejay-hub** [comment]
Hi @KaushikRay thanks for taking the time to suggest the enhancement to the Time Warp component. Support for spanning across multiple days is a common ask so we will definitely add this to the backlog. In fact someone has already sent a pull request with some suggested changes to support this so we'll be taking a look. No promises on **when** it'll be merged into the codebase as we work in our free time on it.

**Comment by KaushikRay** [comment]
Hi @deejay-hub , Thank you for pointing out the pull request. With initial look, it looks there is a new End Date Time variable introduced. I will try to push it and check if it helps with this issue.

**Comment by deejay-hub** [comment]
Multi day events isn't something on the roadmap. The complexities of developing a scalable solution are beyond us at this time.
