### ISSUE TITLE
Support for multiple date fields on same parent/child combination

### ISSUE THREAD

**Issue by KieCap** [deejay-hub/timeline-lwc#110]
**Is your feature request related to a problem? Please describe.**
The use-case is related to two custom objects, the parent with the timeline, and the child which has fields for a _deadline_ date and an _achieved_ date. I'd like to be able to plot both dates on the timeline. In some cases the _achieved_ date may be null, in which case it cannot be plotted (which is fine for this use-case).

**Describe the solution you'd like**
I'd like to be able to create multiple custom metadata types for the same parent/child object combination, but with a different _position date field_. Default functionality could be to simple ignore anything with a null _position date field_ value, but extended functionality could be to have options for handling null values.

**Describe alternatives you've considered**
I believe this will be possible if using separate child objects, but I do not consider this a very good solution.

**Additional context**
n/a

**Comment by deejay-hub** [comment]
Interesting use case @KieCap. We have a pull request to provide the ability to span between 2 dates and wondered if this was a fit for this use case. I have linked the pull request. The basic idea is that you provide a start AND and end date (in your case deadline and achieved). The time warp component then plots the **span** of time between them.

I am wondering if this met your requirement? It seems like seeing the span of time between the deadline vs achieved would be a good fit here but wanted to check. What do you think? Would spanning 2 dates help you?

**Comment by KieCap** [comment]
Hi @deejay-hub. I don't think this will be useful for us in this case specifically. The custom objects I'm referring to are employee development plans, where there is a child object for each certificate the employee is expected to achieve. Each certificate has a deadline, and eventually, an achieved date (which would ideally be before the deadline date). I dont think it is of much benefit to show a span from the achieved date to the deadline date.

What may be useful is to have a span between the record create date (for example, or some other date field) and the deadline date, and then the ability to put the achieved date somewhere in the same row on the timeline. What do you think?

**Comment by deejay-hub** [comment]
I like the concept. I guess it comes down to what we would want the user to get from the feature. For me it would be to 
1. Quickly assess which certificates were achieved 'on-time' which is before or on the deadline vs those certifications that were 'late' which is achieved after the deadline and be able to filter for one or both. 
2. See which certifications nearing their deadlines but not achieved yet (at risk)

What else would you add? We can then look at the best way to implement it.

**Comment by KieCap** [comment]
Yes, definitely both of those would be nice and a good start for us!

**Comment by deejay-hub** [comment]
Closing this as being able to add this functionality in a sufficiently generic way to support many use cases is difficult. People can use the code base and add their specific requirements - then package up a version tailored for their use case.

We want the base open source code base to be as generic as possible.
