### ISSUE TITLE
Update to latest D3 library

### ISSUE THREAD

**Issue by vnehess** [deejay-hub/timeline-lwc#117]
As an ISV, I would like to have one copy of D3 library in my package, to simplify maintenance. We are using D3 V6 today.

I would like to have this timeline library also work well with D3 V6

I've ported most of the known changes, and these are straightforward, however, i still see a bug where each task is positioned at the same Y location.  X locations work as expected

I am looking for advice from others who have tried to upgrade libraries as I am new to D3 development and not ready to send a working pull request back to this project.

**Comment by vnehess** [comment]
Here is the patch in case anyone wants to try the timeline with the D3-v6 library

[d3v6_patch.txt](https://github.com/deejay-hub/timeline-lwc/files/6177908/d3v6_patch.txt)

**Comment by deejay-hub** [comment]
Thanks @vnehess. We don't plan to actively work on this in the short term but will keep it open, for now, in case others in the community want to help and to gauge if this is important to other too.

**Comment by deejay-hub** [comment]
Updating to v7.0.0 release 28 days ago. Will test over the next week but the linked pull request looks good so far.

**Comment by RupertBarrow** [comment]
A bit off subject - sorry.
Have you @deejay-hub @vnehess managed to get D3 **v2** examples running in LWC ?  If so, which version precisely ?
I cannot get it to load into LWC : probably too old Javascript syntax, or something like that.
