### ISSUE TITLE
Longer timeframe

### ISSUE THREAD

**Issue by marcbourlon** [deejay-hub/timeline-lwc#134]
**Is your feature request related to a problem? Please describe.**
I am using this **fantastic** component for a medical doctor. It is very important for her to see the complete patient's history (encounters, interventions, calls, emails, etc.), for convenience, but also because it's a legal obligation to keep records for at least 7 years. Not being able to go back in time more than 5 years is unpleasant, because the timeline appears empty in the past, giving the impression nothing happened before, and simply put, the convenience of using the component as a great navigation tool is lost.

**Describe the solution you'd like**
I would actually remove the limitations/pre-defined timeframe. What is the reason behind limiting it, instead of letting people decide when too much is too much? I guess there are some performance issues, as well as readability issues. But in such a case, there are actually very few elements to display on the timeline, so it would not impact much, I think.
If such removal is impossible, I would extend the past to as much as possible (10 years minimum, 15? 20?)
5 years in the future is fine, though for things like routine examination (cancer checks...), one might want to plan ahead more, but I don't have this need.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by deejay-hub** [comment]
Added 1.5, 4, 6, 7, 8, 9 and 10 year options to future and historic time ranges

**Comment by marcbourlon** [comment]
Brilliant! Thanks a lot.
