### ISSUE TITLE
Is it possible to configure the application to filter via Contact/Account Name and if so, how?

### ISSUE THREAD

**Issue by bgado25** [deejay-hub/timeline-lwc#147]
Hello, I just came across this application and was really pleased with the demo and putting it to work myself. Something I would like to ask in order to enhance its capability for where I work is, is it possible to configure the application to be able to filter via Contact/Account Name? When attaching the app to the Contacts Page, I can filter based off of Tasks, Events, Files | Notes, Cases etc., however I need the functionality of being able to filter based on Contact or Account Names to see which users have interacted with each specific case. I read in the configuration guide about something called Dot Notation and it leads me to believe that it is possible to configure the code somehow, I just simply don't know where to begin as I have just began looking into practicing and learning APEX. Any help, guidance or assistance would be greatly appreciated, thanks in advance.

**Comment by deejay-hub** [comment]
Hi @bgado25 thanks for taking the time to raise a suggestion for improvement. To get a better understanding of what you'd like to see can I ask you to expand on 'the ability to see which users have interacted with a case'? Is this which users have updated a case record - or perhaps it's which contacts have been associated to a case? Would you be able to explain how you would envisage this working? Thanks!

**Comment by bgado25** [comment]
Hi @deejay-hub, thank you very much for the swift response. So at my current company, we have our Activity Timeline setup to display _emails_ that are sent to _contacts_. With that view, it display a preview of the subject line, the sender and the receiver as shown in the image below:
![image](https://user-images.githubusercontent.com/76118199/135639571-5b620e7f-92f2-4a3e-add4-a6627a48a69c.png)
I am trying to figure out how to setup the Time Warp Application so that on the Activity Timeline, it mimics what our current Activity Timeline does just utilizing the timeline format of the App, i.e. shows an email icon to inform the user that the specific instance involves an email transaction, and then when you hover over the email icon, it will display the subject line, the sender and receiver name. Below is an image that portrays what I am hoping to accomplish (I copy and pasted the portion circled in red because that is the result I need, however I don't know how to configure the app to display that result). I simply need to be able to see any email transactions made on the Timeline notated by the email icon, and when I hover over the icon, the subject line along with the sender and receiver name are displayed. Also, being able to filter based on who sent the email would really help too, however the only portion I absolutely need is being able to see emails plotted on the timeline.
![image](https://user-images.githubusercontent.com/76118199/135640636-9e0b22dd-491b-41e6-b333-358e4bd4beac.png)

As for expanding on "the ability to see which users have interacted with a case", that actually just falls into what I described above, I just didn't fully capture the scope of what my company wanted to accomplish. So all in all, the only functionality I need is to be able to see emails being plotted on the timeline and when you hover over the email icon, it provides the subject, to and from information. And as aforementioned, being able to filter the timeline based on who the sender or receiver is would be fantastic, however just having the emails plotted on the timeline would be more than enough. Hopefully this captures what I am hoping to accomplish as opposed to my first post. Let me know if you need me to further explain anything or if this functionality is already setup in the default setup, and I am just doing something wrong. Thank you so much for your time once again.

**Comment by deejay-hub** [comment]
Thanks for that. That is much clearer. Emails are typically logged as tasks and as such would be plotted by default on the Time Warp component. Here are emails shown under a Contact. 

![image](https://user-images.githubusercontent.com/7021883/135739928-53f08bb6-88d8-40af-9c8f-1ffd286ab513.png).

It works based on the assumption that the activity sub type for the record is set to 'Email' - which is the default behaviour.

There are 2 exceptions. The first is indirect relationships and the second is Enhanced Email.

### Indirect Activities
For example if the parent object in your screenshot is an Account then you may not see the activity emails for related Contacts by default. If I assume that you need the emails set to Contacts shown on the Account record then you can find the instructions in the Knowledge Base - https://salesforce.quip.com/6yvoAcBukqZB

Just search for the following sections:

**Accounts have tasks and Events in the standard Timeline component that don’t show in Time Warp. How come?**
**What about indirect relationships? The standard Account timeline shows tasks and events not directly linked to the Account. Can Time Warp do something similar?**

### Enhanced Email
The other possibility is that you're using 'Enhanced Email'. This uses the EmailMessage object and might be bypassing Tasks altogether. 

![image](https://user-images.githubusercontent.com/7021883/135740092-6abc21b1-e4a7-49ba-ac82-ea8c2c5e248b.png)

This might need you to add some new metadata records to the setup. Are you using Enhanced Email?

As for seeing who sent and received the email. The hover over popup uses the Fallback Tooltip field on the custom metadata type. So you can use dot notation to add the person you sent the email to by using Who.Name

![image](https://user-images.githubusercontent.com/7021883/135740857-0a5f5a56-18e5-4617-9a93-1586f2c98437.png)

Which would make the hover appear as follows:

![image](https://user-images.githubusercontent.com/7021883/135740837-6d535548-8e5b-4600-8c7a-f3bf49d4a342.png)

Or if you needed From and To you could create a custom field and use Apex to populate the value as "From: x To: y" and specify that field instead.

**Comment by deejay-hub** [comment]
Did you have any luck @bgado25 ? We will close this issue in 7 days under the assumption that you managed to get it working.
