### ISSUE TITLE
Setting up OpenActivity and ActivityHistory on Account gives SOQL error

### ISSUE THREAD

**Issue by absuptAlmbrand** [deejay-hub/timeline-lwc#153]
**Describe the bug**
I followed the guide [here](https://quip.com/6yvoAcBukqZB) under the heading:
**What about indirect relationships? The standard Account timeline shows tasks and events not directly linked to the Account. Can Time Warp do something similar?**
Setting up the new records as directed

But when the new metadata is active I get the following errors. Depending on which one is active.

`SObject row was retrieved via SOQL without querying the requested field: OpenActivity.ActivitySubtype : Class.bmpyrckt.TimelineService.getFieldValues: line 381, column 1 Class.bmpyrckt.TimelineService.getTimelineRecords: line 275, column 1`

`SObject row was retrieved via SOQL without querying the requested field: ActivityHistory.ActivitySubtype : Class.bmpyrckt.TimelineService.getFieldValues: line 381, column 1 Class.bmpyrckt.TimelineService.getTimelineRecords: line 275, column `

**To reproduce**
1. Follow the linked guide
2. go to an Account
3. switch to the Time Warp view

**Expected behaviour**
I would expect the time warp to show Tasks and events linked to the related Contacts.

**Screenshots**
![2021-10-18 10_09_56-Custom Metadata Types _ Salesforce](https://user-images.githubusercontent.com/58294515/137693229-17829f95-37ff-4023-b309-b57cf53a3525.png)

![2021-10-18 10_10_41-Custom Metadata Types _ Salesforce](https://user-images.githubusercontent.com/58294515/137693272-9c9bd4ea-9851-45e2-ae1f-c650b6739dd0.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser: chrome
-   Version: 94.0.4606.81

**Comment by deejay-hub** [comment]
Hi @absuptAlmbrand.... can we confirm a couple of things.

- What **version** of Time Warp have you got installed? Setup->Apps->Packaging->Installed Packages. Then search for Time Warp and look at the version number.

- Are you using **Person Accounts**?

- Can we confirm with the settings above _inactive_ that the Time Warp loads successfully.

That will help us replicate the issue.

**Comment by absuptAlmbrand** [comment]
Hi @deejay-hub

1. The installed Time Warp version is 1.5
2. Yes we are using Person Accounts
3. If I deactivate the settings time warp works as expected

**Comment by absuptAlmbrand** [comment]
I will start with updating Time Warp then.
I will be in touch when we are done.
