### ISSUE TITLE
Unable to plot data from a custom object with a namespace

### ISSUE THREAD

**Issue by manufacturersalliance** [deejay-hub/timeline-lwc#155]
**Time Warp version**
Setup->Apps->Packaging->Installed Packages. What is the value in the Version Number column for the package Time Warp.
1.9

**Describe the bug**
When attempting to plot data from a custom object with a namespace, nothing is appearing.

**To reproduce**

1. View by going to contact record and looking at timeline for a contact that has related attendee records
2. Go to 'Custom Metadata Types, Timeline Configuration'
2. Click on 'Manage Records'
3. Scroll down to 'Contact_Attendees'

**Expected behaviour**
I expect to see the attendee records associated with the contact appear as plots
**Screenshots**
https://www.screencast.com/t/9vtCTx5oK

**Desktop (please complete the following information):**

-   OS: [e.g. iOS] Windows 10
-   Browser [e.g. chrome, safari] Chrome
-   Version [e.g. 22] Version 95.0.4638.69 (Official Build) (64-bit)

**Additional context**
I am happy to get onto a call to troubleshoot if needed.

Thank you in advance!

**Comment by deejay-hub** [comment]
Thanks @manufacturersalliance. It looks like you're trying to plot the relationship between Events and Attendees if I look at the metadata you've setup but the screen shows Contact.  The EventApis__Attendees__r describes the relationship between Events and Attendees so would be the config you need if you wanted to drop the time warp onto the **Event** object. So you could try to add the time warp component to the Event page and it should work.

For **Contact**, if I am understanding it correctly you'll need to use the relationship defined by the Lookup to Contact (Event__Contact__c) so drill down on this field on the Attendee object to see what the relationship name is and then overwrite the current value you have (I suspect it would be something like 'EventApis__Contacts__r').

If you're still having trouble email me at david.norris@mulesoft.com and we can go through it online.

**Comment by deejay-hub** [comment]
Looks like it was an issue with the relationship name field. Using a managed package means the format was EventApi__Attendees__r. Once we used the correct value we could get the records to plot successfully. I also find using the developer console helpful to check your query runs successfully 

SELECT Id, (SELECT Id, Name, XXX__c from XXX__r) FROM Contact WHERE Id='XX'

Where XXX__c are custom fields you are plotting and XX__r is the relationship name field.
