### ISSUE TITLE
Consider removing or replacing moment.js

### ISSUE THREAD

**Issue by deejay-hub** [deejay-hub/timeline-lwc#16]
**Is your feature request related to a problem? Please describe.**
moment.js is a fairly large library - alternatives like luxon are available. Load times could be improved.

**Describe the solution you'd like**
Perhaps consider improving component load time by replacing moment with luxon

**Describe alternatives you've considered**
Since the only functions used are add, subtract and diff - consider removing the need for a third party and implement functions yourself

**Comment by adrian-cg** [comment]
Have you considered date-fns? With webpack (or w/e bundler) you could probably build the static resource with only the functions that are used, and the API is very similar to moment.

I'll give it a shot later this week and report back.

**Comment by deejay-hub** [comment]
I haven't considered date-fns. Luxon and rewriting using vanilla JavaScript have been mentioned up until now. I guess the key criteria is either to remove it completely OR for a substantial reduction in resource size. I'm totally open to ideas! **Thanks for looking into it**.
