### ISSUE TITLE
Not seeing any Events related to custom object.

### ISSUE THREAD

**Issue by brian23gt** [deejay-hub/timeline-lwc#161]
Version 1.9

I do not see any Event being plot in a custom object ( from a managed package ).
The custom object API is flair__Location__c

I created the custom metadata type, and added the component in the record page but I don't see anything even tho i have events related to this object with a lookup relationship. 

<img width="1148" alt="Screenshot 2021-12-13 at 16 04 58" src="https://user-images.githubusercontent.com/96066289/145836427-6334a643-89af-4055-8015-f3d6350911cf.png">
<img width="692" alt="Screenshot 2021-12-13 at 16 05 32" src="https://user-images.githubusercontent.com/96066289/145836497-78fd7c4b-3d09-44f1-95e4-4687eabbbb8c.png">

Proof of event related to the flair__Location__c object : 
<img width="1287" alt="Screenshot 2021-12-13 at 16 07 51" src="https://user-images.githubusercontent.com/96066289/145836967-179afe7d-9411-4b2e-a48d-2fbcdf9e0783.png">
 

-   OS: Mac OS Big Sur 11.6
-   Browser Chrome

**Comment by deejay-hub** [comment]
Hi @brian23gt. Given your current metadata you have asked to plot the Events where the WhatId is the Location record. In other words any events that look like this

![image](https://user-images.githubusercontent.com/7021883/145898466-31dd2f7d-df92-45c2-95b5-a8d13e9e90c1.png)

That seems to work okay. 

If you need to add a custom field to Activity (called Location__c) then expect to be able to plot this on the Time Warp then that is something we don't currently support.

**Comment by brian23gt** [comment]
> Hi @brian23gt. Given your current metadata you have asked to plot the Events where the WhatId is the Location record. In other words any events that look like this
> 
> ![image](https://user-images.githubusercontent.com/7021883/145898466-31dd2f7d-df92-45c2-95b5-a8d13e9e90c1.png)
> 
> That seems to work okay.
> 
> If you need to add a custom field to Activity (called Location__c) then expect to be able to plot this on the Time Warp then that is something we don't currently support.

Thanks for your reply, yes that's what i thought. The events are related to the contacts. I just have a custom lookup field where i reference a location. I thought this was possible with time warp, am I wrong? Or is it not working only with events.

**Comment by brian23gt** [comment]
For example if i use another object, Which is a copy of the Event, it does work and i am using a lookup relationship too.
<img width="1123" alt="Screenshot 2021-12-14 at 09 20 40" src="https://user-images.githubusercontent.com/96066289/145960049-055e8443-e797-4654-9614-ab43c4250b83.png">

**Comment by brian23gt** [comment]
If i can't make it work with Event, i could use the custom object that is working, but i would like to redirect the user to the event record.
I see that there is a field "Drilldown Id Field" but it doesn't seem to work. I referenced a text field where i copy the 15 or 18 digits ID but it's not working :

SObject row was retrieved via SOQL without querying the requested field: Treatment_Event__c.HT_Booking_ID__c : Class.bmpyrckt.TimelineService.getFieldValues: line 411, column 1 Class.bmpyrckt.TimelineService.getTimelineRecords: line 299, column 1

**Comment by brian23gt** [comment]
Perfect, thanks a lot for the quick support. Have a nice day

**Comment by deejay-hub** [comment]
TimelineService was not assigning the value in the drilldown field variable to the SOQL inner select statement. It was incorrectly assigning the tooltip value. This meant that when the field was accessed later it was not available since it was never included in the original query.

_From v1.5_
String drilldownIdField = String.valueOf(tcr.**tooltipIdField**);

_Added to luyten release_
String drilldownIdField = String.valueOf(tcr.**drilldownIdField**);
