### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by JoelJiang** [deejay-hub/timeline-lwc#171]
**Time Warp version**
Luyten / 1.10.0

**Describe the bug**
I get install error "You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary."

<img width="617" alt="1" src="https://user-images.githubusercontent.com/99577769/153740578-e0eea6e2-e11c-49db-a5e1-df875c8d0d4d.png">

**Comment by deejay-hub** [comment]
Hi @JoelJiang. Would you be able to provide us 2 things to help us investigate.
1. Screenshots of every screen you go through when you click 'Get It Now' from the AppExchange so we can see which options you select as you go through? 
2. Confirmation that the user you are using to complete the install has the 'Download AppExchange Packages' system permission assigned to their profile.
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/7021883/153747272-580c85ec-8bf6-4de4-9333-7f1f3b5eba3b.png">

**Comment by JoelJiang** [comment]
Dear Deejay,



Thanks, I fixed it with your second suggestion, I didn’t know who untick that checkbox, before I could install package. Thanks again.


Best Regards,

Joel Jiang
Sr Consultant,Technology Solutions
[IQVIA logo_96dpi_100pxheight]
Learn more<http://www.iqvia.com/> about IQVIA(tm)

7F, Crystal Plaza T1, No.191 Yaolong Road, Pudong New District, Shanghai, P.R.China
上海市浦东新区耀龙路191号晶耀前滩T1办公楼 7楼
M: +86 13681643655

发件人: Dave Norris ***@***.***>
发送时间: 2022年2月13日 17:38
收件人: deejay-hub/timeline-lwc ***@***.***>
抄送: Jiang, Chaoqun ***@***.***>; Mention ***@***.***>
主题: Re: [deejay-hub/timeline-lwc] Installing Error (Issue #171)


Hi @JoelJiang<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJoelJiang&data=04%7C01%7Cchaoqun.jiang%40cn.imshealth.com%7C3af0e7c6c1974ac889d208d9eed47a37%7C5989ece0f90e40bf9c791a7beccdb861%7C0%7C0%7C637803418620472449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u7ebbApAWQ3Tlcfo66BTAkb0Xl0hOChRPbaH79TkCSE%3D&reserved=0>. Would you be able to provide us 2 things to help us investigate.

  1.  Screenshots of every screen you go through when you click 'Get It Now' from the AppExchange so we can see which options you select as you go through?
  2.  Confirmation that the user you are using to complete the install has the 'Download AppExchange Packages' system permission assigned to their profile.

[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7021883%2F153747272-580c85ec-8bf6-4de4-9333-7f1f3b5eba3b.png&data=04%7C01%7Cchaoqun.jiang%40cn.imshealth.com%7C3af0e7c6c1974ac889d208d9eed47a37%7C5989ece0f90e40bf9c791a7beccdb861%7C0%7C0%7C637803418620472449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=019V4Baevoc068K6E2Wc9Ntj9JT%2FqWPBFn0QbOBQbW8%3D&reserved=0>

―
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdeejay-hub%2Ftimeline-lwc%2Fissues%2F171%23issuecomment-1037964436&data=04%7C01%7Cchaoqun.jiang%40cn.imshealth.com%7C3af0e7c6c1974ac889d208d9eed47a37%7C5989ece0f90e40bf9c791a7beccdb861%7C0%7C0%7C637803418620472449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FzYI2tR7Bj6ABHnxm5E1oQKycZQ3mFB9I5znzK%2Bn09w%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXXW7KM56NXQTIIUH7RPSGTU253WFANCNFSM5OIJGGYA&data=04%7C01%7Cchaoqun.jiang%40cn.imshealth.com%7C3af0e7c6c1974ac889d208d9eed47a37%7C5989ece0f90e40bf9c791a7beccdb861%7C0%7C0%7C637803418620472449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pAT07xB3OSLKfl2HFCTxwtywbkr7LnA8Qk7r0SpTWg0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchaoqun.jiang%40cn.imshealth.com%7C3af0e7c6c1974ac889d208d9eed47a37%7C5989ece0f90e40bf9c791a7beccdb861%7C0%7C0%7C637803418620472449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eqf9wvHnR3tZY5ALuwAtR5RRxa4%2Fyw7Y059jZiLOMRU%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchaoqun.jiang%40cn.imshealth.com%7C3af0e7c6c1974ac889d208d9eed47a37%7C5989ece0f90e40bf9c791a7beccdb861%7C0%7C0%7C637803418620629103%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JDHPI4%2B%2FSguhNxDzjqzujn2%2BW8dR4jgRT3sRBj6RABo%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>


________________________________________
IMPORTANT - PLEASE READ: This electronic message, including its attachments, is CONFIDENTIAL and may contain PROPRIETARY or LEGALLY PRIVILEGED or PROTECTED information and is intended for the authorized recipient of the sender. If you are not the intended recipient, you are hereby notified that any use, disclosure, copying, or distribution of this message or any of the information included in it is unauthorized and strictly prohibited. If you have received this message in error, please immediately notify the sender by reply e-mail and permanently delete this message and its attachments, along with any copies thereof, from all locations received (e.g., computer, mobile device, etc.). To the extent permitted by law, we may monitor electronic communications for the purposes of ensuring compliance with our legal and regulatory obligations and internal policies. We may also collect email traffic headers for analyzing patterns of network traffic and managing client relationships. For further information see our privacy-policy<https://www.iqvia.com/about-us/privacy/privacy-policy>. Thank you.

**Comment by deejay-hub** [comment]
Glad you got it working. Good luck. Closing this issue out.
