### ISSUE TITLE
Installation Fails with "Data Not Available"

### ISSUE THREAD

**Issue by schnism** [deejay-hub/timeline-lwc#173]
**Time Warp version**
 Luyten v1.10 - Jan 2022

**Describe the bug**
When installing the App in our sandbox I get an eMail,  Subject "Sandbox: Package Time Warp Install Failed"

```
Problem:

1. (de) Data Not Available
The data you were trying to access could not be found. It may be due to another user deleting the data or a system error. If you know the data is not deleted but cannot access it, please look at our <A href="{0}" title="support{1}">support</a> page.

2. (fr) Data Not Available
The data you were trying to access could not be found. It may be due to another user deleting the data or a system error. If you know the data is not deleted but cannot access it, please look at our <A href="{0}" title="support{1}">support</a> page.
```

**To reproduce**
Open https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3u00000ONnm7EAD
click on "get it now"
login to sandbox
click on "install for all users"

**Expected behaviour**
App is installed and usable

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser Chrome 
-   Version 98.0.4758.82

**Comment by deejay-hub** [comment]
Hi @schnism. Looks like this is a known issue at Salesforce. Nothing specific to this package. As far as I can tell it looks like a patch will be rolled out in the next 48 hours that will automatically resolve the issue. I will also cross link to the known issue when it is available.

I'll get back to you when I think it's fixed and get you to try again.

**Comment by deejay-hub** [comment]
@schnism This is the link to the known issue https://trailblazer.salesforce.com/issues_view?id=a1p4V000000pMUlQAM. Currently looks like it's been fixed in most Orgs. I would try again and let us know the outcome.

**Comment by schnism** [comment]
Many thanks, this was really the issue, it is solved now also on our sandbox.

Sorry for bothering here, as it actually was no timeline-lwc-issue.
