### ISSUE TITLE
Setup Error - unexpected token 

### ISSUE THREAD

**Issue by jaimedh10** [deejay-hub/timeline-lwc#175]
**Time Warp version**
1.10

**Describe the bug**
I would like to use the Custom Object (Project__c) as a Parent Record, but instead i get the error message shown in the screenshot below.
Previously, i created a new a Custom Metadata Type as the second screenshot illustrates.

**Screenshots**
![image](https://user-images.githubusercontent.com/58445753/157638085-d3b3f620-6f76-4f83-be08-c2763f04e31e.png)
![image](https://user-images.githubusercontent.com/58445753/157638906-cff9b60a-3323-41ff-a454-c7fe8f10f45e.png)

**Desktop**
-   OS: Windows 10 Home
-   Browser: Chrome
-   Version 99.0.4844.51

**Comment by deejay-hub** [comment]
Hi @jaimedh10 the entity type Activity doesn't support queries. If you want to plot Tasks and Events then you would need to use Task and Event and use 2 records to set them up.

This one to plot tasks related to your project record.

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/7021883/157796290-87b76f95-161b-4cca-9dbe-af3951127f83.png">

This one to plot events related to your project record.

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/7021883/157796426-5f4baee3-f715-45da-a75a-89dcf35fe48b.png">

Try that and let us know how you got on.

**Comment by jaimedh10** [comment]
Thanks @deejay-hub! It's working as expected now :)
