### ISSUE TITLE
Include Quote in the Account Timeline

### ISSUE THREAD

**Issue by montse74** [deejay-hub/timeline-lwc#176]
**Is your feature request related to a problem? Please describe.**

Even though in the documentation it says "Time Warp allows different related records to show per object and supports lookup and master detail relationships. ", I am incapable to include the Object QUOTE to the ACCOUNT timeline. 

**Describe the solution you'd like**

I will like to include it in the Custom Metadata Types.

**Describe alternatives you've considered**

**Additional context**

**Comment by deejay-hub** [comment]
Hi @montse74 thanks for raising the issue. The Quote relationship to Account unfortunately isn't made available to query via a standard relationship. In fact I believe you still can't have a standard related list on the Account page for the Quote object. Salesforce would have to provide this functionality for Time Warp to use it. Here's the idea that can be up voted.

https://ideas.salesforce.com/s/idea/a0B8W00000Gdjc1UAB/add-native-quotes-related-list-on-accounts

To implement this functionality we would have to include a specific query for this object which would impact performance too much to consider. For this request we'll add it when the capability from Salesforce becomes available.
