### ISSUE TITLE
Scratch Org creation fails

### ISSUE THREAD

**Issue by benjaminloerincz** [deejay-hub/timeline-lwc#183]
**Time Warp version**
Current master branch version.

**Describe the bug**
Creation of scratch org fails, throws this error:

> ERROR running force:org:create:  The ancestorId for ancestorVersion 1.9.0 can't be found. Package ID TimeWarp. 
> 
> Try this: 
> The ancestor package version [1.9.0] specified in the sfdx-project.json file may exist hasn’t been promoted and released. Release the ancestor package version before specifying it as the ancestor in a new package or patch version.

**To reproduce**
Execute this as described in README

> git clone https://github.com/deejay-hub/timeline-lwc
> cd timeline-lwc
> sfdx force:org:create -s -f config/project-scratch-def.json -a timewarp-lwc

**Expected behaviour**
Scratch org creation is successful.

**Desktop (please complete the following information):**

-   OS: MacOS Monterey 12.3.1 (21E258)
-   CLI Version: sfdx-cli/7.146.1 darwin-x64 node-v16.14.2

**Comment by deejay-hub** [comment]
@benjaminloerincz we could make the instructions clearer so will add a step to help.  The sfdx-project.json file needs to be updated for local installations. Yours should look like below. Can we get you to overwrite your version of the file with the details below and let us know the outcome? If successful we'll add the instruction to the readme.

```
{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true,
            "package": "TimeWarp"
        }
    ],
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "53.0"
}
```
