### ISSUE TITLE
Support for Incident Management Data Model

### ISSUE THREAD

**Issue by gehretfranck** [deejay-hub/timeline-lwc#185]
Salesforce has introduced a new data model for Incident Management

- https://www.salesforce.com/products/service-cloud/features/incident-management/
- https://help.salesforce.com/s/articleView?id=sf.incident_mgmt.htm&type=5

The Incident Management solution introduces 3x new standard objects : 
1. Incident
2. Problem
3. Change Request

This would be great if the the component could support those 3x new objects.

Thanks !

**Comment by deejay-hub** [comment]
@gehretfranck thanks for the suggestion.

Version 1.10 should support the new data model - assuming you create the metadata records yourself.

I just wanted to confirm whether you have the latest version installed and have added the metadata but still can't get it to work? Or are saying that you can get the new objects to work but would like them included with default records in the metadata like some other objects?

Can you clarify?

**Comment by deejay-hub** [comment]
Seems to be okay when we test it. Here is a screenshot of an Incident with Child Incidents and Linked Articles plotted
<img width="714" alt="image" src="https://user-images.githubusercontent.com/7021883/165890667-3e4c017e-e5c6-4850-b9d7-b100adaa4906.png">

**Comment by gehretfranck** [comment]
Hi !

Sorry I should have been more explicit :-)

By saying "support" what I had in mind was having default metadata for
Incident. Like the ones for Tasks and Events on Account. This could be
helpful :

   -  user/admin may not read the "error message" and could believe the
   component is not working properly
   - As example for admin to create their own

I understand that it is nearly impossible to have default metadata for
every object but I strongly believe this component will be used a lot for
Incident Management
Thank you very much.

**Comment by deejay-hub** [comment]
Gotcha. Sounds reasonable. Here are the Parent and Child Relationships that I'll add for the next release. If there are any missing then just comment and let me know.
**Incident**
	ChildIncidents
	Events
	Tasks
	ChangeRequestRelatedIssues
	CaseRelatedIssues
	ProblemIncidentRelatedIssues
	LinkedArticles
	ContentDocumentLinks

**ChangeRequest**
	Events
	Tasks
	LinkedArticles
	ContentDocumentLinks
	NewWorkPlans
	NewWorkSteps
	ProcessSteps

**Problem**
	Events
	Tasks
	LinkedArticles
	ContentDocumentLinks
	CaseRelatedIssues
	ChangeRequestRelatedIssues
	ProblemIncidentRelatedIssues
	ProblemIncidents
	ProblemRelatedItems
