### ISSUE TITLE
Extend the maximum History Time Range

### ISSUE THREAD

**Issue by CathyInMN** [deejay-hub/timeline-lwc#201]
**Is your feature request related to a problem? Please describe.**
The maximum History Time Range is currently only 10 years. For our subscription-based business, we'd like to be able to view a customer's subscription purchases over their lifetime and it is common for our customers to have literally decades of interaction with us. The past 10 years is too small of a time period to be useful to us. 

It's currently difficult to sort through the purchase records over decades of annual purchases to easily see the trends (there are various levels that can be purchased), the starts & stops in the subscriptions, etc. The timeline component would make this so much easier to view. We would restrict the volume of data involved for the component by having a very limited set of objects that can even show on the timeline (probably only 1 or 2) and there would typically be a maximum of one purchase per year for a customer. 

**Describe the solution you'd like**
We would like the maximum History Time Range to be longer -- say 80 or even 100 years to cover a person's working lifetime. 

This might also require a modification of the zoom range? Not clear on that aspect, but we'd want the scale of the component to be appropriate for a timeline that covers decades of time. 

(I'll point out too that this enhancement could be really useful for the Health Cloud world to be able to view a patient's lifetime medical history in a very visual way.)

**Describe alternatives you've considered**
Don't see an alternative for us. If the maximum is not extended, we probably cannot use this app to view this subscription information.  

**Additional context**
N/A

**Comment by deejay-hub** [comment]
@CathyInMN this sounds like a good suggestion. Hopefully members of the community will contribute some changes to bring this to life.

**Comment by deejay-hub** [comment]
Hi @CathyInMN no one in the community has picked this up for a year now. Extending the time range beyond 10 years isn't currently on the roadmap so we're going to close this issue. If someone in the community wants to take this on then we would welcome the contribution.
