### ISSUE TITLE
Problem with updating project.json file

### ISSUE THREAD

**Issue by benjec83** [deejay-hub/timeline-lwc#202]
Time Warp version
Current master branch version.

Describe the bug
When I copy and paste your code into the project.json file

**To reproduce**

1. Overwrite the project-sfdx.json file with the following
2. Problem:  Object is missing property versionNumber required by property package.

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser Chrome
-   Version [103.0.5060.134]

**Comment by dave-mule** [comment]
Hi @benjec83 we'll update the instructions to. Does that solve your issue?
{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true
        }
    ],
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "54.0"
}

**Comment by benjec83** [comment]
Hi @dave-mule - yes, that works. Thank you
