### ISSUE TITLE
Filter out Event Clones

### ISSUE THREAD

**Issue by TobsenMB** [deejay-hub/timeline-lwc#209]
Your Component is one of our users top features available. 
But there is an issue thats plaguing us currently: 
When adding Salesforce Users on the Events "Attendee" standard field, Salesforce is creating technical needed clones of these Events. I think Salesforce does so in order for the Event to show up in the personal Calendars of the users. 
In the Standard Activity Component these clones are filtered out. 
But not in the Timeline as shown below for an Event with four Attendees:

![image](https://user-images.githubusercontent.com/111737648/185881251-19d4c7ba-107b-4073-9842-a622424bfdef.png)

**Solution**
There is a way to identify these Cloned Events: 
The Standard Event field "IsChild" shows true if the Event is a technical clone Record. The original Event will show "false" in this field.
If we would able to filter these Events out from the component this would be rather cool.
Not sure if this should be done by default (who would ever want to see such clones?) or by setting in the Event Metadata config. 

**Contribution**
Based on your feedback and solution Ideas we could also invest some time to participate on the development of such feature here in this project. 

Thanks again for such cool Component!

**Comment by deejay-hub** [comment]
Hi @TobsenMB thanks for raising this use case. This isn't something I had come across before. Looks like you're plotting the standard Account -> Event relationship here. One thing I'd love you to try is switching to the ActivityHistory and OpenActivities relationships. This is what the standard timeline would use and AFAIK would remove the duplicates in question.

To see a step by step guide on which metadata to switch head to the FAQ doc (https://quip.com/6yvoAcBukqZB) and search for the section '_What about indirect relationships? The standard Account timeline shows tasks and events not directly linked to the Account. Can Time Warp do something similar?_' then make the change suggested and try again. 

Using this method I not only start to see indirect relationships (like the standard timeline) e.g. Events related to a Contact of the Account but not directly to the Account) but it will also remove the duplicate.

**Give it a go and let me know if you think this can work**. The added advantage is that in the filter you'll see Open Activities/Activity History that can be filtered separately.

**Comment by TobsenMB** [comment]
Hi @deejay-hub!
This worked like a charm. 
Thank you so much for your support

**Comment by thomasops** [comment]
Hey @deejay-hub !
Thanks for all the hard work on the Timeline.
I've followed the steps in the 'What about indirect relationships' section. It worked perfectly for the Account objet. But I have the same issue (child events are showing in the timeline) on the Opportunity object.

Is there any way to do the same for the opportunity object?
Thanks again for the amazing component ! 😃

![CleanShot Jan 9 2025](https://github.com/user-attachments/assets/24ba6595-43ae-42db-bb3b-c436eaf9e45a)
