### ISSUE TITLE
Add "First Activity" to Zoom Based On configuration

### ISSUE THREAD

**Issue by juanjoseblancob** [deejay-hub/timeline-lwc#224]
The Zoom Based On configuration parameter (picklist with options Current Date or Last Activity) of the LWC is great. However, I feel it lacks a 3rd option in the picklist that's also very typical: First Activity.

Just as 'Last Activity' works by positioning the zoom on the last related record (chronologically), First Activity would work by positioning the zoom on the **first** related record.

Extra Credit :)

With those 3 options most use cases would be covered, but if not too hard actually adding a 4th one (Centered) would be huge. That option would work by positioning the zoom approximately in the middle (chronologically) of all dates. I realize this may be significantly harder, and not as generically useful as 'First Activity'.

**Comment by deejay-hub** [comment]
Sounds like a great idea @juanjoseblancob. We'll work on it for inclusion in the next release.
