### ISSUE TITLE
Ability to Add Another Detail Column

### ISSUE THREAD

**Issue by mayday6971** [deejay-hub/timeline-lwc#228]
I have rolled this out to my users and they did have one feedback item. This would be simply the addition of another field to be shown in the popup display. For example, when viewing a Case object, I see the following fields:

- Subject
- Status
- Case Owner
- Severity
- CaseNumber

They have asked for another column to be added to the display, specifically Case Origin (Origin). They have also asked for the Record Type name, but I saw that the enhancement request is on another issue. 

I think adding in a new field should be simple enough requirements-wise.

My suggestion though would be to use the Compact Layout and the fields on that layout, if this were my dream request. That would be even better as it basically shows whatever fields you would like it to show and is easier for awesome admins and developers alike to adjust without too much effort. 

As always, thanks for the amazing work!

**Comment by deejay-hub** [comment]
Hi @mayday6971 . By happy coincidence the hover for Cases should already be driven from the Compact Layout. Here's one showing 8 fields.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/7021883/201417437-84f27415-ae22-4a62-8cbf-c15998d01e7b.png">

You can also have different fields showing for each record type by assigning the Compact Layout accordingly.

What are you seeing? Have you changed the compact layout? Have you assigned the Compact layout to the correct profiles? Does the user have access to all fields you're seelcting?

1. Add a new compact layout to the Case page
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/7021883/201417924-6b9bccab-8b35-4f25-97f5-7cea9dfd34f3.png">

2. Make sure you override the record type assignments with the new compact layout
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/7021883/201418288-4fe9da3d-474f-49aa-84df-097df8bbee26.png">

**Comment by deejay-hub** [comment]
@mayday6971 we haven't heard from you. We'll leave the issue open for another week then close off and assume you got this working.
