### ISSUE TITLE
Time Warp limitation at Account level is not showing all records for companies with too many items 

### ISSUE THREAD

**Issue by rmaibm** [deejay-hub/timeline-lwc#236]
**Time Warp version**
V.1.11

**Describe the bug**

On our Account pages, on Sales & Marketing Timeline tab, we have a Time Warp module. It displays Opportunities, Tasks, as well as some custom Objects such as Marketing Interactions, Client Interests, Patterns of Interests, etc.

When Accounts have too many of those records associated with them,  in Time Warp, some records do not show up, randomly. Usually an entire record type stops to show after a date. (For example, Opportunities stopped appearing for an account in TimeWarp after Nov 2022, even though there are many Opportunities after that)

We know there is a hard limit of 50,000 records, but the Accounts are not showing 50,000, they start to have problems with just a few thousands.

We need Time Warp to support the theoretical 50,000 records limit   OR  at least  provide consistent data , showing the most recent records properly, and dropping the oldest records when the practical limit is reached.

We followed the instructions on the Time Warp documentation, but none of them helped
We tried many changes since November: limiting date range to 2 years, then 1.5 years, upgrading Time Warp to 1.11, etc, but none resolved the issue.

**Expected behaviour**

1  - Please verify why Time Warp is dropping records randomly at a very low limit (not near 50k records)

2  - Please make sure Time Warp can expose all 50k records, or, if there is a lower limit, please provide a way so Time Warp can expose newer records and drop older records, considering all record types

**To reproduce**

1 - Go to an Account object > Sales Marketing Timeline tab > Time Warp Module, 
2 - Providing that you get an Account with many many records, You can see records in TimeWarp will stop showing after a date, even though there are more recent records.

**Screenshots**

![Screenshot 2023-02-16 at 10 58 09](https://user-images.githubusercontent.com/30326167/219401413-7a609d8b-c5c9-4381-8a8d-905cbe4c72e6.png)

![Screenshot 2023-02-16 at 10 59 28](https://user-images.githubusercontent.com/30326167/219401311-783c54a5-a0c1-4bef-bb46-afb3ea4849f7.png)

**Desktop (please complete the following information):**

-   OS: MacOS Ventura
-   Browser: Chrome
-   Version:  Version 109.0.5414.119

**Comment by deejay-hub** [comment]
Hi @rmaibm. Thanks for letting us know about your issue. In order for us try replicate.

1. Would you be able to supply the metadata setup you have for Account - so we can see the child records you are plotting and values for the Position Date and Detail Fields? We need to be able to see all the fields on each child record.
2. Can you give us the time range you're using - 1, 3,5, 10 years etc?
3. Can you give us an approx. number of records for each child (2,000 Tasks, 1,000 Contacts, 5,000 X. etc)
4. Can you inactivate the metadata records and re activate them one at a time to see if you can determine which child record causes the issue.
5. Can you check to see if you are using a Large Text Area data type in any metadata record.

We have a known issue for Large Text Area fields documented here (https://github.com/deejay-hub/timeline-lwc/issues/104) which would perhaps cater for the issue you're seeing but would need you to confirm. If you're using the Fallback Tooltip field then it's recommended not to use a field that has a Large Text Area data type.

**Comment by rmaibm** [comment]
Thanks -- I'm collecting the responses from my Dev team

**Comment by rmaibm** [comment]
Hello @deejay-hub , et al

1 - Attached the plotting and values for the position date and details fields for account object.
2 - we are using 1.5 yrs time range.
3 - I need to get some numbers, I will give you some ranges for now, I will get actuals soon:

- Opportunities  (1-3k)
- Tasks  (1-3k)
- Client Interests (300)
- Marketing Touchpoints (2-5k)
- Patterns of Interest (6)

4 - didn't find the activate and re activate option, how can we do that?
5 - there are not any Large text area data type in metadata record. attached the screen print for  metadata record.
We do have some Text Area fields (not in metadata) , but we introduced those recently, and the problem  in Time Warp was already happening.

<img width="1097" alt="Screen Shot 2023-02-17 at 8 38 26 AM" src="https://user-images.githubusercontent.com/30326167/220105989-f03c5595-b1a0-4913-8b68-5076a1d0a61d.png">

<img width="1124" alt="Screen Shot 2023-02-17 at 8 44 30 AM" src="https://user-images.githubusercontent.com/30326167/220106003-cdf1cc27-7d61-410e-8964-d31cfbcf6b8b.png">

**Comment by deejay-hub** [comment]
Thanks @rmaibm that helps.

I was hoping to get a screenshot like this one for item 1 - for each child object you're plotting.

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/7021883/220220781-c2fe654b-9086-4a51-bc0c-86599d7a0f90.png">

That way I can see the API names for the fields you use for each configurable field. Then for each field you see in the screenshot when you take it - it would be great to know their corresponding data type.

This is our best shot to recreate the issue.

For point 4 we're hoping to get an indication that if you inactivate all options but one does Time Warp start plotting the remaining records successfully. For example, try inactivating Account_Tasks by setting the Active field value to false.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/7021883/220221064-502551a8-8fc0-4fd8-bc5e-23ffe5b69413.png">

Then see if the remaining children get plotted. If not repeat for another child. We're trying to see if the issue is related to one particular metadata record OR just related to volume of records.

**Comment by rmaibm** [comment]
Hello, please find the screenshots attached 


![Screen Shot 2023-02-21 at 9 04 30 AM](https://user-images.githubusercontent.com/30326167/220450220-9ee8d3d2-f3d2-49a1-8084-6acd5c000223.png)
<img width="1133" alt="Screen Shot 2023-02-21 at 8 59 35 AM" src="https://user-images.githubusercontent.com/30326167/220450231-4d9b19e4-6943-46bc-a553-99e05bda4742.png">
![Screen Shot 2023-02-21 at 9 03 30 AM](https://user-images.githubusercontent.com/30326167/220450250-01b486c7-89a6-4a3e-b3f1-cdae5c7a47eb.png)
![Screen Shot 2023-02-21 at 9 03 53 AM](https://user-images.githubusercontent.com/30326167/220450255-2c3ce541-73db-4281-8121-c8eb34a8c77e.png)
![Screen Shot 2023-02-21 at 9 04 14 AM](https://user-images.githubusercontent.com/30326167/220450257-65ad60b6-b28a-4a2f-a065-9d471c8aa750.png)

**Comment by deejay-hub** [comment]
Hi @rmaibm. Thanks for your time pulling that together. It looks like for the Account_Tasks record you are using **Description** in the Fallback Tooltip Field. Description is a large text area field and causes a known issue that might explain your issue.

Can you please update this record to be another field. Perhaps try **Status**. Then report back to see if this changes the _missing records_ behaviour?

Once we know if this fixes the issue we can get back to you with how you might be able to display the description using an alternative route.

**Comment by rmaibm** [comment]
Thanks ! We will do the change and let you know when it can be tested -- It will take a few days.

**Comment by rmaibm** [comment]
Planning to be able to test next Monday Mar 6

**Comment by rmaibm** [comment]
The data displayed in the Time Warp module has improved greatly. We are still testing, I will let you know if we still notice items missing. I will check if the Content Owners want the Tasks to show the description instead of status . If they want that, what is the process to re-enable it? Do we need a formula field that replicated a display just an excerpt (100 chars~) ? 
Thanks in advance!

**Comment by rmaibm** [comment]
@deejay-hub ^^^

**Comment by deejay-hub** [comment]
@rmaibm A formula field would work but AFAIK Salesforce prevents you using large text area fields in formulas (and related list columns). You would have to create a custom text field (100 chars~) then use Flow Builder or Apex to take the first x chars from the standard Description field and put it in the new custom field. Any existing records you would have to update in batch. Then you would use the new custom field in the fallback tooltip field.

**Comment by rmaibm** [comment]
Thanks, I will work on that change . I will keep this ticket open until I hear back from some more users to confirm the removal of the Large Text Area field from Tasks resolved the entire problem. I will get back to you March 15.

**Comment by rmaibm** [comment]
Thanks all

**Comment by deejay-hub** [comment]
Glad you got it working. We'll make the need for no large text areas more prominent in the config guide.
