### ISSUE TITLE
Vertical chronology 

### ISSUE THREAD

**Issue by swood09** [deejay-hub/timeline-lwc#24]
Most chronological feeds in Salesforce Lightning are vertical; case feed, activity feed, etc. It would be nice to incorporate this chronological feed in a manor consistent with users expectations of the Salesforce UI.

**Describe the solution you'd like**
Add attributes to the implementation that allow admins/devs to control orientation of layout. Include ability for bottom-to-top and top-to-bottom chronology.

**Comment by deejay-hub** [comment]
Adding to the backlog to design the mobile layout including support for desktop narrow regions. We're working on a similar look and feel to Google Photos timeline. If you have any suggestions please let us know.

**Comment by chazzvader** [comment]
This is a wonderful idea, and much needed for this product.  Vertical orientation so we can have the component live on a side panel, have filter/search capabilities for users to find any relevant records in the timeline sorting you currently do.  
Very useful.  I would be able to use this product in a number of places, if it had this vertical orientation.

**Comment by deejay-hub** [comment]
Closing this as there are already vertical timelines available for free on the AppExchange.

https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000G0yN3UAJ
