### ISSUE TITLE
Custom metadata type not showing on timeline

### ISSUE THREAD

**Issue by chinyan1** [deejay-hub/timeline-lwc#240]
**Time Warp version**
Version 1.11
**Describe the bug**
We are unable to add our custom objects to the time line. Unsure if it is due to the way our org is setup or if it is how we are writing the custom meta data type to plot them. We need some insight into what we are doing wrong.

**To reproduce**
1. Create custom meta data type using the format noted in the configuration and save the record.
2. Return to a record page with the time line component on the page.
3. Scroll through timeline looking for record for custom meta data type we created.
4. Nothing shows on the component for that custom meta data type.

**Expected behaviour*
The expected behavior is that we see records for all metadata types that we create custom metadata type for in setup.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: macOS Monterey and Windows 10
-   Browser Chrome/Safari

**Comment by deejay-hub** [comment]
Hi @chinyan1. We have created a detailed config guide here that might help you https://quip.com/ahFCA9VBEKtr it contains instructions for different types of objects.

If the above doesn't help then you can take a look at this example https://github.com/deejay-hub/timeline-lwc/discussions/166

If that doesn't work then you'd have to include a screenshot of the metadata (see above discussion for the info on which screens we would need to see to get back to you asap)

**Comment by deejay-hub** [comment]
Hi @chinyan1 just following up to see if you've had any success plotting your objects on Time Warp? Do you need any further assistance?

**Comment by deejay-hub** [comment]
Hi @chinyan1. We'll keep this issue open for another week then assume you have managed to solve this issue. If you still need help we just need clarification on the metadata setup in Timeline_Configuration__mdt.
