### ISSUE TITLE
Custom object added in Timeline configuration metadata with Parent as Account not showing records for PersonAccount

### ISSUE THREAD

**Issue by meerajoysf** [deejay-hub/timeline-lwc#243]
**Time Warp version**
1.11
**Describe the bug**
We added a custom object (Will and Preferences) to the Timeline Configuration metadata and it is active. Parent Object is Account. Followed everything as per the configuration guide. In the UI, we have navigated to a Person Account record (record type of Account). Even though it has child records for Will and Preferences, it is not showing up in the timeline. Please note, it shows records when we navigate to a Organization account

**To reproduce**
1. Create a custom metadata record under Timeline configuration as per the guide with Parent Object as Account
2. Return to the PersonAccount record where timeline component is added.
3. Scroll through the timeline component and provide the required time range. The child records for Will & Preferences not listed.

**Expected behaviour**
The child records for Will & Preferences should be listed for all record types of Account

**Screenshots**
<img width="888" alt="Screenshot 2023-04-07 at 9 13 14 AM" src="https://user-images.githubusercontent.com/130121995/230536578-a14fc67a-a8ed-42d6-9037-c9171b32bc3e.png">

<img width="1157" alt="Screenshot 2023-04-07 at 9 14 01 AM" src="https://user-images.githubusercontent.com/130121995/230536633-735c2f1b-9fb7-4c16-bdbd-f6b212607f85.png">

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser [e.g. chrome, safari]: Chrome
-   Version [e.g. 22] 111.0

**Additional context**

**Comment by deejay-hub** [comment]
Hi @meerajoysf. When you're on a Person Account record Time Warp looks for records in the Timeline_Configuration__mdt where the Parent Object field has a value for PersonAccount.

So you'll need to duplicate the metadata record above and set the Parent Object to PersonAccount to get the same records plotted for the Person Account AND Business Account.

Let us know if that makes sense.

**Comment by meerajoysf** [comment]
Thank @deejay-hub for the response. Yes, it works with PersonAccount as Parent.
