### ISSUE TITLE
Add User's related activities

### ISSUE THREAD

**Issue by antodrd** [deejay-hub/timeline-lwc#249]
I would like to use Timeline in order to display activities related to a user. 
The user is the activity owner of multiple activities which have a forecast date. I would like to see these activities on the timeline of a user's profile.
Is it possible ? 

I face an error trying to set it up : " unexpected token: 'FROM' : (bmpyrckt) ".

**Comment by deejay-hub** [comment]
Hi @antodrd. Time Warp uses SOQL relationship queries to allow child records to be plotted. For the User SObject Salesforce does not provide the ability to write a query like this SELECT Id, (SELECT Id from Tasks) FROM User to get activity records based on ownership. So your use case could only be supported by you adding the code needed to query the Task and Event objects directly.
