### ISSUE TITLE
Multirealtionship on CASE for CONTACT

### ISSUE THREAD

**Issue by hsimonnet** [deejay-hub/timeline-lwc#25]
**Describe the bug**
After using timeline it appears that the timeline class does not support multi relationship on Contact object to Case

**To reproduce**
1. Go to schema builder and add 2 or more relationship (lookup) with Case (see screenshot schema builder below)
![schema](https://user-images.githubusercontent.com/19706073/74159707-7ee5b500-4c1c-11ea-8275-1af807199df7.png)

2. Click on the refresh button of the timeline, and no cases appear unless you have to insert correct data on Contact.
3. See error/incorrect code related to the timeline cls

The generated SOQL syntax use lookup relation with the incorrect name (see CASES__r or Opportunities1__r ) see extract of my log file after addin some debug log:

15:16:12.639 (6831849000)|USER_DEBUG|[121]|DEBUG|** hugu ** (SELECT Id, Name, CreatedDate FROM Opportunities1__r WHERE CreatedDate>= LAST_N_MONTHS:36 AND CreatedDate <= NEXT_N_MONTHS:6),(SELECT Id, Subject, ActivityDate, TaskSubtype, Description FROM Tasks WHERE ActivityDate>= LAST_N_MONTHS:36 AND ActivityDate <= NEXT_N_MONTHS:6),(SELECT Id, Campaign.Name, CreatedDate FROM CampaignMembers WHERE CreatedDate>= LAST_N_MONTHS:36 AND CreatedDate <= NEXT_N_MONTHS:6),(SELECT Id, Subject, CreatedDate FROM **Cases__r** WHERE CreatedDate>= LAST_N_MONTHS:36 AND CreatedDate <= NEXT_N_MONTHS:6),

**Expected behavior**
So that why we do not see on my instance the cases in relation with my contact.
The problem is coming from the object description you search and the code line where you use it in a map object to put the relation name.
You replace all the time the relation key/value and get this SOQL error syntax depending on the number of lookup setup.

You probably have to modify the code **getChildObjects** line N°194:

    private static Map<String, String> getChildObjects(String Obj, Map<String, Schema.SObjectType> schemaMap) {
		Map<String, String> childRelatedObjects = new Map<String, String>();
		List<Schema.ChildRelationship> objectRelationships = schemaMap.get(Obj).getDescribe().getChildRelationships();
		for (Schema.Childrelationship eachRelationship : objectRelationships) {
			if (eachRelationship.getChildSObject().getDescribe().isAccessible()
			        && !eachRelationship.getChildSObject().getDescribe().getLabel().contains('History')
                    && eachRelationship.getRelationshipName() != null
                    && eachRelationship.getRelationshipName() !='Cases__r') {
                        System.debug('/// hugu /// '+ String.valueOf(eachRelationship.getChildSObject()) + '--' + String.valueOf(eachRelationship.getRelationshipName()));
				childRelatedObjects.put(String.valueOf(eachRelationship.getChildSObject()), String.valueOf(eachRelationship.getRelationshipName()));
			}
        }
        
        System.debug('/// hugu final /// '+childRelatedObjects.values());
		return childRelatedObjects;
	}

**Screenshots**
with this workaround, I get my cases into the timeline
![codemodify](https://user-images.githubusercontent.com/19706073/74160675-0d0e6b00-4c1e-11ea-9a1a-8b173b5b92be.png)

**Additional context**
Feel free to chat me internal Salesforce

**Comment by deejay-hub** [comment]
Awesome description. Thanks for the detail.

If I'm understanding the problem correctly the issue stems from the fact that the Apex class is looking up the relationship name based on the SObject. This is the same issue document in issue #10 .

What we are proposing to do is add a relationship field to the Timeline_Configuration__mdt for the Admin to specify the relationship name to use.  This will allow support for mutliple relationships to the same object. It's slightly less user friendly for the administrator who has to know the relationship name but ultimately more flexible.

**Comment by eschweitzer78** [comment]
Hi DJ, this would actually also fix issues for PersonAccounts -- they indeed have multiple relationships for Events, Tasks, and Cases, one for Account and the other one for Contact.

Thanks

**Comment by deejay-hub** [comment]
@hsimonnet This issue should now be resolved. In fixing the issue you can now specify multiple records for a child object with different relationship names. So you could plot Cases for a Contact with different relationship names now specified in the metadata type.
