### ISSUE TITLE
Ability to use variable to set icon and background color

### ISSUE THREAD

**Issue by sylg** [deejay-hub/timeline-lwc#267]
**Is your feature request related to a problem? Please describe.**

I'm syncing data (especially events like Web page, offline interactions, etc )to SFDC and want to only use one CMT. in my event table I have a column that indicates the type of event (Webinar, Offline visits, etc) and I can easily generate the icon / background color in code.  

It would be nice if I could use a field of the (custom) object like `event_type_icon__c` to pick the icon. event_type_icon__c will be a path to the icon obv.

**Comment by deejay-hub** [comment]
Sounds like a good idea. We'll try it out to see what the level of effort is in adding for January.

**Comment by deejay-hub** [comment]
This has now been addressed on the code base. Scheduled to be packaged in the AppExchange version in January. Feel free to check it out in a scratch org. Details [here](https://dave-norris.medium.com/time-warp-roadmap-jan-2024-2837cbee21b1?source=friends_link&sk=edc57ce4d00b14371ff552f7a7bc537c).

**Comment by sylg** [comment]
That’s awesome, thanks Dave!
