### ISSUE TITLE
Show/Hide Button

### ISSUE THREAD

**Issue by macalmon** [deejay-hub/timeline-lwc#273]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
On the LWC itself have a button next to the refresh and filter button to show/hide the timeline.

**Describe alternatives you've considered**
- Creating a boolean field on the object and setting component visibility if TRUE shows timeline, but that involved updating the record. the field would have to be on all object record pages that I put the timeline on
- Looking for some LWC code that I could mash with your code, but I'm not a developer so I really don't know what I'm doing

**Additional context**
This would allow the viewing user to expand/collapse the timeline.

**Comment by deejay-hub** [comment]
Hi @macalmon could you help us understand the use case here. An Admin could put Time Warp in a sub tab on the page that would facilitate the use case to optionally show/hide based on a click. This has the added benefit that the component doesn't load until the user clicks the tab. Could you help us better understand what benefit the button would bring?

![timeline-hide](https://github.com/deejay-hub/timeline-lwc/assets/7021883/45c80ed5-acf0-4aa1-8fa6-e8c7446727cd)

**Comment by macalmon** [comment]
@deejay-hub When I think about putting the timeline on a record page I think about having it stretching across the page - is it a "Timeline" after all :)

<img width="1406" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/31143160/9428660c-3d63-4e56-8418-0bfbecbf593e">

**Comment by deejay-hub** [comment]
Can't you add the Tabs component to the full width area? In your case since you use Quick Links you could divide the full width between Time Warp and Quick Links..that way the user can view or hide Time Warp using the tab.
![timeline-width](https://github.com/deejay-hub/timeline-lwc/assets/7021883/95af410c-c7e8-4b03-a5ad-0d73cf1a2b5a)

**Comment by macalmon** [comment]
Ah thank you
