### ISSUE TITLE
Support Professional Edition Installation

### ISSUE THREAD

**Issue by mtebusi** [deejay-hub/timeline-lwc#280]
**Is your feature request related to a problem? Please describe.**
I have a client that is currently on Professional Edition of Salesforce (with API access add-on) and is very interested / excited about the possibility of the Time Warp application. Upon install, it returns a few errors related to Enterprise-specific features that are not enabled in the destination org. I understand that there may be reasons that this is suited for Ent only, but curious if there are a few small tweaks that could potentially enable this for all Professional Edition users?

**Describe the solution you'd like**
Allowing the deployment of the application to Professional Edition orgs by modifying key components that are preventing install currently. Namely, the following Apex Classes which throw the following error: `Installing this package requires the following feature and its associated permissions: Apex Classes.` 
Classes referenced during install include: 
> classes/TimelineParentPicklist.cls-meta.xml
>classes/TimelineParentPicklist_Test.cls-meta.xml
>classes/TimelineParentPicklist.cls
>classes/TimelineService_Test.cls
>classes/TimelineService_Test.cls-meta.xml
>classes/TimelineService.cls-meta.xml
>classes/TimelineService.cls
>classes/TimelineParentPicklist_Test.cls

And (understandably) all following references to TimelineService throw errors due to the previous feature errors as well: 
>Unable to find Apex action class referenced as 'TimelineService'.

**Describe alternatives you've considered**
Potentially allowing for deployment of the application without activation of those specific dependencies or features, and then allowing some sort of UI 'checkbox' that would enable them within the application. 

**Additional context**
N/A

**Comment by deejay-hub** [comment]
Thanks for raising this @mtebusi. I have never spent any time investigating this but have raised a case with Salesforce to ask what might cause this. In theory, Professional Edition Orgs should be supported by managed packages that have been through a security review - but will ask Salesforce.

<img width="819" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/073aecad-6e33-4a82-8f49-7a802866292b">

I'll update their response here. No ETA.

**Comment by mtebusi** [comment]
Thanks a ton! And happy to beta  test with my client. They are in love with the app / I shared how we would use it at Salesforce in the SDO.

**Comment by deejay-hub** [comment]
Okay @mtebusi Salesforce needed to add a permission to the packaging org to support Professional Edition.

They tell me they've done it so it should now be working.

Do you want to try and install in a PE org - since seeing is believing?

**Comment by mtebusi** [comment]
You're my hero @deejay-hub 
<img width="1127" alt="Screenshot 2024-02-16 at 1 05 23 PM" src="https://github.com/deejay-hub/timeline-lwc/assets/61427842/e0c58461-0710-4174-a4a7-e8d5a5c5e075">
