### ISSUE TITLE
Documentation is not available anymore - Quip

### ISSUE THREAD

**Issue by jbronssin** [deejay-hub/timeline-lwc#284]
Hey,

In the repo and Appexchange links (all the quip links), the quip links are not available anymore as it's asking for a paid Quip Subscription.
Many thanks for your help!
![Capture d’écran 2024-03-26 à 16 40 06](https://github.com/deejay-hub/timeline-lwc/assets/65334819/86836c36-559d-42dc-929d-eeb24927f8d9)

**Comment by deejay-hub** [comment]
I've checked the setup of the document and all looks ok. Can I get you to try opening the links in a private browsing session and let us know if that works?

**Comment by jbronssin** [comment]
Damn, you are totally right...
I would suggest to add the information to the documentation just to be sure not to be bothered by anyone else 😅

Many thanks for your kind answer!
