### ISSUE TITLE
Add EventRelation to TimeWarp

### ISSUE THREAD

**Issue by jbronssin** [deejay-hub/timeline-lwc#288]
Hello,

I'm attempting to incorporate EventRelations into a contact, a lead, and an opportunity within TimeWarp. However, these are not appearing in the Activity Feed, and I need them to be visible to users. Could you provide guidance on how this can be achieved? 

Thank you!

Jb

**Comment by deejay-hub** [comment]
Hi @jbronssin. Have you checked the [documentation](https://quip.com/6yvoAcBukqZB)? We have a section in the Knowledge Base called 'What about multiple contacts to an activity? Our Org has ‘Allow Users to Relate Multiple Contacts to Tasks and Events’ activated but only the primary contact shows. Can I get the Task and/or Event to show for all the contacts related to it? '

This shows the steps for getting TaskRelations and EventRelations onto the Contact. Can you confirm that you've tried this and are still having issues? If so what does the Timeline Configuration metadata look like.

**Comment by jbronssin** [comment]
> Hi @jbronssin. Have you checked the [documentation](https://quip.com/6yvoAcBukqZB)? We have a section in the Knowledge Base called 'What about multiple contacts to an activity? Our Org has ‘Allow Users to Relate Multiple Contacts to Tasks and Events’ activated but only the primary contact shows. Can I get the Task and/or Event to show for all the contacts related to it? '
> 
> This shows the steps for getting TaskRelations and EventRelations onto the Contact. Can you confirm that you've tried this and are still having issues? If so what does the Timeline Configuration metadata look like.

I swear to God... If only I could read the documentation before asking you anything, that's the second time you catch me read handed on that.
It's working like a charm... And you saved my sprint @deejay-hub !

Just a small hint, you should (if I'm correct) modify a tiny bit of the quip documentation in the related part about the EventRelation: The way you show it will generate the "UI API Invalid type" error. One fall back can be "Status" for ex.


Many thanks again for your help! (and your work on that)
