### ISSUE TITLE
Is this possible to display timeline for one object only?

### ISSUE THREAD

**Issue by trusha82** [deejay-hub/timeline-lwc#289]
Hi Team,

I just wanted to let you know that I am not raising any issues. I would like to see if it's possible to set up a timeline for one parent/master object only. 
So my use case is to display the timeline of the case file. e.g. when the case file is created, allocation date, waitlist date, open date, first session date, etc... 
I am capturing everything on the Case file. Is it possible to reflect that on the timeline too?

Please let me know!

Thank you!
Trusha

**Comment by deejay-hub** [comment]
Hi @trusha82 . We don't support plotting fields from the parent object currently - so _not_ possible.

Supporting this requirement would require us to change the logic of Time Warp to accommodate the need to change the start and end dates of the timeline canvas. Currently these are based on the first activity, current date or last activity. We would need to read all field values you have to determine earliest and latest dates.

So it's trickier than it sounds. Let us know if there's anything else you need.
