### ISSUE TITLE
Viewing Error: "Houston..we've had a problem" "Invalid time value"

### ISSUE THREAD

**Issue by andrewalmand-dd** [deejay-hub/timeline-lwc#297]
**Time Warp version**
1.14

**Describe the bug**
Some users are experiencing this error on the TimeWarp widget when viewing records. Seems to impact one user in particular more often (as System Admin) but I have seen it across multiple users.

**To reproduce**
Unsure honestly. Sometimes I can visit the record and I'll see the same error but other times it won't be present on my end. Usually fixes it self and/or is present/not present randomly throughout the day. Just visiting a record can cause it to occur. Visiting the same record at another time and it will be clear.

**Expected behaviour**
TimeWarp widget showing the timeline of tasks.

**Screenshots**
![image (36)](https://github.com/user-attachments/assets/81936e31-c219-4836-97f0-c4527cec40df)

**Desktop (please complete the following information):**
-   OS: Windows
-   Browser: Chrome
-   Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by deejay-hub** [comment]
Intermittent issues are the hardest to fix. We'll spend some time trying to replicate what you're seeing but ultimately need to fund a way to consistently reproduce what you see.

The only thing we need to know is what child objects are you plotting for an Account?

Navigate to Setup-> Custom Metadata Types -> Timeline Configuration - Manage Records

Then query setup a new view for all records where Parent Object = Account
<img width="639" alt="image" src="https://github.com/user-attachments/assets/3476253a-4391-4df3-9362-27bf3524dd18">

This should return a list of child records configured.

<img width="1446" alt="image" src="https://github.com/user-attachments/assets/14389fe7-86d8-4639-a78c-2b8468cd0f43">


Can you take a screenshot of the above in your org? That helps us look into the Date Fields you're using for each object.

**Comment by andrewalmand-dd** [comment]
Hi Dave, thanks for getting back to me!

I can appreciate that these types of intermittent issues are difficult.
When it pops up (seems to have stopped?) I'll instruct my team to try to
identify what they are doing differently so we can hopefully replicate.

In the meantime, I actually have two unrelated questions regarding the app:

   1. We have email activities in our Salesforce account dating upwards of
   2+ years ago but the app will only display the last 1 years worth. Is this
   a setting I need to configure?
   2. We have some instances of email activities displaying on the native
   salesforce activities section but NOT on the timeline view. What could
   cause this? What info would you need from me to investigate?

Let me know what additional info you need for either of these questions.

Thanks,
Andrew
Andrew Almand - Sales Operations Manager
E - ***@***.***
<http://go.datadome.co/b?y=49q24eh268p64d1m75gmccr168oj0d9pccr30cpn6thjgc1m6ss3eoplc4h2o8ji48t24rb1d5m78rpqc5n68sj5esn62r3dc5n68g34c5q62p3fdliisorf48======>
M - +1 813-493-0278
W - datadome.co
<http://go.datadome.co/b?y=49q24eh268p64d1m75gmccr168oj0d9pccr30cpn6thjgc1m6ss3eoplc4h2o8ji48t24q3keho76ehf5ti62t31chnmqp9ecdniu8g=>

[image: App Banner Image]
<http://go.datadome.co/b?y=49q24eh268p64d1m75gmccr168oj0d9pccr30cpn6thjgc1m6ss3eoplc4h2o8ji48t24q3keho76ehf5ti62t31chnmqp9ecdniufrlehmluor1dlo62qb7doun6qb7dpgn8tbickj7at3dbtpmutbicdijqlr9edil6t31dlo2ctbkdlfmqpb4d5qmqfb5dlgmir12>

[image: App Banner Image]
<http://go.datadome.co/b?y=49q24eh268p64d1m75gmccr168oj0d9pccr30cpn6thjgc1m6ss3eoplc4h2o8ji48t24q3keho76ehf5ti62t31chnmqp9ecdniupbmcln78spf48======>

[image: __tpx__]

**Comment by deejay-hub** [comment]
1. We have email activities in our Salesforce account dating upwards of 2+ years ago but the app will only display the last 1 years worth. Is this a setting I need to configure?
No setting needed. We would need to know how many records you have, the date you use to plot the records on the timeline and the date range you specified when adding the component to the page.

3. We have some instances of email activities displaying on the native salesforce activities section but NOT on the timeline view. What could cause this? What info would you need from me to investigate?
Try the FAW https://salesforce.quip.com/6yvoAcBukqZB. See section 'Accounts have tasks and Events in the standard Timeline component that don’t show in Time Warp. How come?'

5. To investigate the first issue we need the screenshots suggested in the previous post.

**Comment by andrewalmand-dd** [comment]
Thanks for the reply here Dave and my apologies on the extended delay.
We're in the final stages of setting up our SF so lots of things going on!

1. I'll try my best to provide you this data but let me know if you need
more info:

   - "how many records you have" - Are you asking how many total email
   records or Contacts / Accounts? Let me know and I'll provide an estimate
   - "date you used to plot the records" - Just changed it to "Activity
   DateTime" although it was recently "ActivityDate". The issue still persists
   when we changed to the date/time version
   - " date range you specified when adding the component to the page" -
   Assuming you're referring to "Historical Time Range (Years)" which is set
   to "3"

2. Solved! Thank you
3. Stopped occurring for now so lets say Solved!

4. *NEW* - I'm struggling with mapping a custom managed object. I've
followed the instructions and I don't get any errors. I just don't see it
on my timelines. I'll share some screenshots of the relevant data+API names
if you can help troubleshoot (see attached and let me know if any of them
don't work).

Thanks,
Andrew
Andrew Almand - Sales Operations Manager
E - ***@***.***
<http://go.datadome.co/b?y=49q24eh2c8q32o9mcgrj4d1i6opmadhnchij8p366ko3ae1i61j32d1n74h2o8ji48t24rb1d5m78rpqc5n68sj5esn62r3dc5n68g34c5q62p3fdliisorf48======>
M - +1 813-493-0278
W - datadome.co
<http://go.datadome.co/b?y=49q24eh2c8q32o9mcgrj4d1i6opmadhnchij8p366ko3ae1i61j32d1n74h2o8ji48t24q3keho76ehf5ti62t31chnmqp9ecdniu8g=>

[image: App Banner Image]
<http://go.datadome.co/b?y=49q24eh2c8q32o9mcgrj4d1i6opmadhnchij8p366ko3ae1i61j32d1n74h2o8ji48t24q3keho76ehf5ti62t31chnmqp9ecdniufrlehmluor1dlo62qb7doun6qb7dpgn8tbickj7at3dbtpmutbicdijqlr9edil6t31dlo2ctbkdlfmqpb4d5qmqfb5dlgmir12>

[image: App Banner Image]
<http://go.datadome.co/b?y=49q24eh2c8q32o9mcgrj4d1i6opmadhnchij8p366ko3ae1i61j32d1n74h2o8ji48t24q3keho76ehf5ti62t31chnmqp9ecdniupbmcln78spf48======>

[image: __tpx__]

**Comment by deejay-hub** [comment]
1. Time Warp doesn't show archived activities (https://help.salesforce.com/s/articleView?id=000385669&type=1). The default is 365 days. I assume that your setup hasn't changed this default. That would explain why you only see 1 year's worth of data. You can either change the value to 3 years or change Time Warp to only show 1 year's worth of history.

2. Plotting a related custom object in a managed package. See this discussion for an example https://github.com/deejay-hub/timeline-lwc/discussions/166

**Comment by andrewalmand-dd** [comment]
Solved on both Dave!

Thanks for your help,
Andrew
Andrew Almand - Sales Operations Manager
E - ***@***.***
<http://go.datadome.co/b?y=49q24eh2ckp62c9p6krjad1l6kpj8oplcksjaohpckr38cpk75hjcp316gh2o8ji48t24rb1d5m78rpqc5n68sj5esn62r3dc5n68g34c5q62p3fdliisorf48======>
M - +1 813-493-0278
W - datadome.co
<http://go.datadome.co/b?y=49q24eh2ckp62c9p6krjad1l6kpj8oplcksjaohpckr38cpk75hjcp316gh2o8ji48t24q3keho76ehf5ti62t31chnmqp9ecdniu8g=>

[image: App Banner Image]
<http://go.datadome.co/b?y=49q24eh2ckp62c9p6krjad1l6kpj8oplcksjaohpckr38cpk75hjcp316gh2o8ji48t24q3keho76ehf5ti62t31chnmqp9ecdniufrlehmluor1dlo62qb7doun6qb7dpgn8tbickj7at3dbtpmutbicdijqlr9edil6t31dlo2ctbkdlfmqpb4d5qmqfb5dlgmir12>

[image: App Banner Image]
<http://go.datadome.co/b?y=49q24eh2ckp62c9p6krjad1l6kpj8oplcksjaohpckr38cpk75hjcp316gh2o8ji48t24q3keho76ehf5ti62t31chnmqp9ecdniupbmcln78spf48======>

[image: __tpx__]
