### ISSUE TITLE
 An error has occurred in the following section: [Exception, DisjunctionsNotSupportedException]

### ISSUE THREAD

**Issue by kbell2uw** [deejay-hub/timeline-lwc#301]
**Time Warp version**
1.14

**Describe the bug**
I receive the following error when clicking Manage Records on the Timeline Configuration Custom Metadata Type: 
An error has occurred in the following section: [Exception, DisjunctionsNotSupportedException]

**To reproduce**
1. Go to Setup - Custom Metadata Types - Click Manage Records next to Timeline Configuration.
2. Click Create New View.
3. Give it a View Name and View Unique Name, and Filter by Field: Label, Operator: Contains, Value: Task, Event.
4. Go back to Setup - Custom Metadata Types - Click Manage Records next to Timeline Configuration.
5. See error - you are now prevented from managing configuration records.

**Expected behavior**
No error when loading the timeline configuration metadata type.

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Edge

**Additional context**
I started getting this error after trying to create a new view of timeline configuration records related to tasks and events. After I saved that view, I started getting this error every time I try to access Manage Records for Timeline Configuration.

**Comment by deejay-hub** [comment]
Hi @kbell2uw I believe this is a Salesforce issue. Does the following article help you
https://help.salesforce.com/s/articleView?id=000384700&type=1

**Comment by kbell2uw** [comment]
Ah, thanks so much! Appreciate the quick find - that resolved the issue!
