### ISSUE TITLE
I couldnt see the oppurtunities in time line 

### ISSUE THREAD

**Issue by krishnakatipally801** [deejay-hub/timeline-lwc#304]
**Time Warp version**
1.14V

**Describe the bug**
I see all the related records but i cant see the oppurtunities associated with it. I double checked the rule and account is associated with opp and attached a screen shot

**To reproduce**
I just inserted the component on account page layout.

**Expected behaviour**
I want to see oppurtunities which are open or at least all oppurtunities associated with it 

**Screenshots**
If applicable, add screenshots to help explain your problem. This helps speed up the triage of the issue.

**Desktop (please complete the following information):**

-   windows 
-   chrome 
-  latest 

![Screenshot 2024-10-01 112839](https://github.com/user-attachments/assets/5fde2f82-092f-43c4-89fe-078c09405bae)

**Additional context**

**Comment by deejay-hub** [comment]
Hi @krishnakatipally801 . Time Warp doesn't plot the standard relationship by default. You will have to goto Setup->Custom Metadata and add the following to the Timeline Configuration.

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/1b87cda2-ac66-4b3e-aa2c-ce600ff1dd7d">

**Comment by krishnakatipally801** [comment]
Thank you, its working I was under impression that Account Opportunities relationship mdt existed and why but totally forgot about the naming after we install the financial package, thanks great help.
