### ISSUE TITLE
Instructions to promote the Timeline LWC to production

### ISSUE THREAD

**Issue by ldelima** [deejay-hub/timeline-lwc#74]
Hi, the component and its instructions are amazing.

Even not having any kind of experience with sfdx, I was able to push it to a scratch Org. The Trailhead module instructions are not compatible with the ones provided here since they show how to build/create LWC in Visual Studio by copying and pasting the code. 

Even when I tried to clone and promote the code from within VS terminal I wasn't able to send it to my dev/production org.

Since you have done a good job by providing instructions on how sfdx and CLI work with a scratch Org, Could you please provide the same instructions to push it to production?

Thanks,

**Comment by deejay-hub** [comment]
Sounds like a great suggestion. What we plan to do is release the component on the AppExchange - this will allow people to install the component in any environment. That would be way easier than including instructions on how to package it yourself.

We plan to do this as soon as we've added Person Account support (Issue #31) and fixed Issue #9

**Comment by deejay-hub** [comment]
Once the AppExchange link is available I'll post here

**Comment by deejay-hub** [comment]
@ldelima a release on the AppExchange is close. As someone who requested an easier way to install the component I have created a listing on the AppExchange. It is private at the moment but will be made public soon https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000GXVf4UAH
